# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGYNlSRmBG5ttwW-Ln_E_Eldij5BN_JG
"""

import streamlit as st
import requests
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime

# --- CONFIGURACIÓN DE TELEGRAM ---
TELEGRAM_TOKEN = "8658903767:AAElo1E8owhyDASHgBHUfeMR03an1nJgLfk"
TELEGRAM_CHAT_ID = "8800841732"

# --- CONFIGURACIÓN DE GOOGLE SHEETS ---
# Necesitas un archivo credentials.json de Google Cloud en tu carpeta
SCOPES = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
# Asegúrate de compartir tu Google Sheet con el correo que sale en tu credentials.json
NOMBRE_PLANILLA = "Reservas_Taller_Linares"

SERVICIOS = [
    "Escáner automotriz", "Cambio de luces", "Instalación de alarma",
    "Cierre centralizado", "Mecánica general"
]
HORARIOS = ["09:00", "11:00", "14:00", "16:00"]

def enviar_telegram(mensaje):
    """Envía un mensaje a tu celular vía Telegram."""
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    datos = {"chat_id": TELEGRAM_CHAT_ID, "text": mensaje}
    try:
        requests.post(url, data=datos)
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

def conectar_sheets():
    """Se conecta a Google Sheets y devuelve la hoja de cálculo."""
    creds = ServiceAccountCredentials.from_json_keyfile_name("credentials.json", SCOPES)
    cliente = gspread.authorize(creds)
    return cliente.open(NOMBRE_PLANILLA).sheet1

# --- INTERFAZ WEB CON STREAMLIT ---
st.set_page_config(page_title="Reserva Taller", page_icon="🚗")
st.title("🚗 Reserva tu Hora - Taller Mecánico")
st.write("Completa los datos para agendar tu servicio.")

# 1. Selección de datos
servicio = st.selectbox("Seleccione el servicio:", SERVICIOS)
fecha = st.date_input("Seleccione la fecha:")
fecha_str = fecha.strftime("%d/%m/%Y")

# 2. Lógica para filtrar horarios ocupados
try:
    hoja = conectar_sheets()
    registros = hoja.get_all_records()
    # Buscar qué horas están tomadas para ese servicio y ese día
    ocupados = [fila["Horario"] for fila in registros if fila["Servicio"] == servicio and fila["Fecha"] == fecha_str]
    libres = [h for h in HORARIOS if h not in ocupados]
except Exception as e:
    st.error("Error al conectar con la base de datos.")
    libres = HORARIOS # Si falla sheets, permite mostrar horarios para no bloquear la prueba

if not libres:
    st.warning(f"Lo sentimos, no hay horas disponibles para {servicio} el {fecha_str}.")
else:
    horario = st.selectbox("Seleccione el horario disponible:", libres)
    nombre = st.text_input("Nombre y Apellido:")
    telefono = st.text_input("Teléfono (ej: +569...)")

    # 3. Botón de Agendar
    if st.button("Confirmar Reserva"):
        if not nombre or not telefono:
            st.error("Por favor, completa tu nombre y teléfono.")
        else:
            with st.spinner("Procesando tu reserva..."):
                try:
                    # Guardar en Google Sheets
                    hoja.append_row([nombre, telefono, servicio, fecha_str, horario])
                except Exception as e:
                    st.warning("Se procesó la reserva pero hubo un detalle con Google Sheets.")

                # Enviar notificación a Telegram
                msg = f"🔔 NUEVA RESERVA\n👤 {nombre}\n📱 {telefono}\n🔧 {servicio}\n📅 {fecha_str} a las {horario}"
                enviar_telegram(msg)

                st.success("✅ ¡Tu hora ha sido agendada con éxito! Te contactaremos pronto.")